---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES:
  - CSHARP_CSHARPIER
  - JSON_PRETTIER
  - YAML_PRETTIER
  - DOCKERFILE_HADOLINT

# If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
#ENABLE:
# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - CSHARP_CSHARPIER # formatter
  - JSON_PRETTIER # formatter
  - YAML_PRETTIER # formatter
  - YAML_YAMLLINT # code quality
  - DOCKERFILE_HADOLINT # code quality
  - COPYPASTE_JSCPD # code quality
  - REPOSITORY_DEVSKIM # security vulnerabilities, insecure coding practices
  - REPOSITORY_DUSTILOCK # dependency confusion attack
  - REPOSITORY_GITLEAKS # security vulnerabilities, secrets, hard-coded credentials, API keys, and other sensitive data that should not be stored in a version control system
  - REPOSITORY_TRIVY # vulnerabilities in packages
  - SPELL_MISSPELL # correct commonly misspelled English words
# DISABLE:
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_LINTERS:
EXCLUDED_DIRECTORIES: ["/bin", "/obj", "/.idea", "/.git", "/Migrations"]
