name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: 
      - 'develop' # DEV
      - 'release/**' # QA
      - 'main' # PROD
  pull_request:
    branches:
      - 'main' # UAT
  
jobs:
  integration:
    uses: dmamulashvili/webapi-msa-template/.github/workflows/integration.yml@main
    
  deploy_to_dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    environment: 
      name: Development
      url: https://dev.example.com
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
  deploy_to_qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release/**'
    
    environment:
      name: QA
      url: https://qa.example.com
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    
