name: Continuous Integration

on:
  push:
    branches: [ "main" ]
    
jobs:
  super-linter:
    uses: dmamulashvili/webapi-msa-template/.github/workflows/super-linter.yml@main
  dotnet:
    needs: [super-linter]
    uses: dmamulashvili/webapi-msa-template/.github/workflows/dotnet.yml@main
