name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  super-linter:
    uses: dmamulashvili/webapi-msa-template/.github/workflows/super-linter.yml@main
  dotnet-build-test:
    needs: [super-linter]
    uses: dmamulashvili/webapi-msa-template/.github/workflows/dotnet-build-test.yml@main
