name: Continuous Integration

on:
  workflow_call:
    
jobs:
  super-linter:
    uses: dmamulashvili/webapi-msa-template/.github/workflows/super-linter.yml@main
  dotnet:
    needs: [super-linter]
    uses: dmamulashvili/webapi-msa-template/.github/workflows/dotnet.yml@main
